scst: Fix recently introduced checkpatch complaints about whitespace
Fix two instances of the following checkpatch errors:

ERROR: code indent should use tabs where possible
ERROR: spaces required around that ':' (ctx:VxW)