Merged revisions 6682-6691 via svnmerge from svn://svn.code.sf.net/p/scst/svn/trunk
........
  r6682 | bvassche | 2015-11-12 09:43:26 -0800 (Thu, 12 Nov 2015) | 1 line
  
  scst_copy_mgr: Fix indentation
........
  r6683 | bvassche | 2015-11-12 10:26:26 -0800 (Thu, 12 Nov 2015) | 8 lines
  
  qla2x00t: Suppress a Coverity complaint about a potential buffer overflow
  
  Coverity reported the following:
  
  Copy into fixed size buffer (STRING_OVERFLOW)
  fixed_size_dest: You might overrun the 17 byte fixed-size string
  ha->model_number by copying def without checking the length.
........
  r6684 | bvassche | 2015-11-12 10:30:15 -0800 (Thu, 12 Nov 2015) | 1 line
  
  qla2x00t: Do not compare an array pointer with NULL
........
  r6685 | bvassche | 2015-11-12 10:30:42 -0800 (Thu, 12 Nov 2015) | 1 line
  
  qla2x00t: Use strlcpy() instead of strcpy()
........
  r6686 | bvassche | 2015-11-12 14:17:59 -0800 (Thu, 12 Nov 2015) | 4 lines
  
  scst_lib: Avoid using 64-bit divisions
  
  Reported-by: Sebastian Herbszt <herbszt@gmx.de>
........
  r6687 | vlnb | 2015-11-12 15:33:45 -0800 (Thu, 12 Nov 2015) | 3 lines
  
  Update the root README regarding QLogic target driver
........
  r6688 | bvassche | 2015-11-13 08:26:09 -0800 (Fri, 13 Nov 2015) | 8 lines
  
  scst: Fix kernel 2.6.36 build
  
  Avoid that compilation fails with the following error message:
  
  include/linux/slub_def.h:246: error: conflicting types for ‘kmalloc’
  include/scst/backport.h:458: error: implicit declaration of function ‘kmalloc’
........
  r6689 | bvassche | 2015-11-13 11:07:10 -0800 (Fri, 13 Nov 2015) | 7 lines
  
  scstadmin: Do not try to clear copy manager assignments
  
  This patch avoids that the following error message is displayed on the
  console while "/etc/init.d/scst start" is executed:
  
  scst: scst_cm_mgmt:3556:***ERROR***: Device copy_manager_tgt not found
........
  r6690 | bvassche | 2015-11-13 13:07:50 -0800 (Fri, 13 Nov 2015) | 1 line
  
  scstadmin: Leave out the copy manager from the driver list
........
  r6691 | bvassche | 2015-11-13 17:07:27 -0800 (Fri, 13 Nov 2015) | 4 lines
  
  scstadmin: Pass $PREFIX to Makefile.PL
  
  Signed-off-by: Alexey Mochkin <alukardd@alukardd.org>
........